### PR TITLE
Fix unwrapped oveflowed code blocks not showing scroll bars when setting "Wrap long lines in code blocks" to "No" in "Theme tweaks"

### LINKED ISSUE #8278: [BUG] Unwrapped overflowed codeblocks not showing scroll bars
### Describe the bug

Setting "Wrap long lines in code blocks" to "No" in "Theme tweaks" cause the code to overflow.

图片

While the code blocks rendered by highlight.js shows a scroll bar under the code blocks.

### Expected behavior

A scroll bar should be shown under the overflowed code block.

The style `overflow-x: auto` should be applied to the element.

### To Reproduce

_No response_

### Screenshots

_No response_

### TiddlyWiki Configuration

Tiddlywiki 5.2.4 prerelease

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Leilei332**
This PR fixes #8278 

图片

### CODE REVIEW

**Comment by pmario** [comment]
It's important to add: 

**Setting "Wrap long lines in code blocks" to "No" in "Theme tweaks" cause the code to overflow.**

**Comment by pmario** [comment]
> Inline code should not follow "Wrap long lines in code blocks" option

This last change is not backwards compatible. So why should this setting not effect inline code?

**Comment by Leilei332** [comment]
> > Inline code should not follow "Wrap long lines in code blocks" option
> 
> This last change is not backwards compatible. So why should this setting not effect inline code? 

In my opinoin, the setting "Wrap long lines in code blocks" should only affect code blocks, not inline code.

**Comment by pmario** [comment]
>In my opinoin, the setting "Wrap long lines in code blocks" should only affect code blocks, not inline code.

The initial changes where a bugfix, which does not really need discussion. 

I think the last change should be undone and the PR should only contain the bugfix. 

The extra change is an opinion, which may need discussion. As it is implemented, it completely removes the line `white-space: {{$:/themes/tiddlywiki/vanilla/options/codewrapping}};` without any replacement. So this changes the behaviour of the whole CSS rule.

**Comment by Leilei332** [comment]
The commit has been reverted. I think it's better to create a new pull request about it.

**Comment by pmario** [comment]
@Jermolene -- could you review this one?

**Pull request merged**
