### PR TITLE
Fix $:/temp/advancedsearch displayed in Shadow search

### PR DESCRIPTION
**Pull request by Leilei332**
Fix the problem introduced in #8678.

图片

### CODE REVIEW

**Comment by Leilei332** [comment]
Actually I wonder whether we should use `-` for convenience or `:except` for readability here.

**Comment by pmario** [comment]
>Actually I wonder whether we should use - for convenience or :except for readability here

In the core verbosity is preferable. So it's easier to understand if users want to modify it. So I think it's OK the way you did it.

**Comment by BurningTreeC** [comment]
Hi all, so sorry about this mistake! Thanks @Leilei332 for spotting this bug!

**Comment by Jermolene** [comment]
Thanks @Leilei332 

> > Actually I wonder whether we should use - for convenience or :except for readability here
> 
> In the core verbosity is preferable. So it's easier to understand if users want to modify it. So I think it's OK the way you did it.

Yes indeed. We might prefer to say "clarity" than "verbosity"

**Pull request merged**
