### PR TITLE
Add empty message to tag picker, search dropdown and advanced search

### LINKED ISSUE #8343: [IDEA] Show message when tagpicker dropdown is empty
The dropdown is not good, arguably even confusing, when showing up empty like so:

image

I propose to show some message like `(no search result)` or `(no tag exits containing that string)` or `(empty)` or some such.

### PR DESCRIPTION
**Pull request by Leilei332**
Implement feature described in #8343 and closes #8343 .

The count widget in `$:/core/ui/AdvancedSearch/Shadows` and `$:/core/ui/AdvancedSearch/System` is replaced by the count filter operator to let the conditional shortcut work.

### CODE REVIEW

**Comment by Leilei332** [comment]
Since the *Standard* page in advanced search is implemented in a strange way and exists a problem (see #8485 ), adding empty message to it will be postponed.

**Comment by pmario** [comment]
>Since the Standard page in advanced search is implemented in a strange way and exists a problem (see https://github.com/TiddlyWiki/TiddlyWiki5/pull/8485 ), adding empty message to it will be postponed.

If you want to postpone #8485 you should make it a draft too.

**Comment by Leilei332** [comment]
Actually #8485 is ready to be merged now. I intended to add empty message to the *Standard* tab after it is merged.

**Comment by Jermolene** [comment]
Thanks @Leilei332 looks good

**Comment by Jermolene** [comment]
Thanks @Leilei332

**Pull request merged**
