### PR TITLE
docs: fix typo in a wikilink

### PR DESCRIPTION
**Pull request by jeremyredhead**
just like the title says 

---
<small>Submitted using https://saqimtiaz.github.io/tw5-docs-pr-maker/.</small>

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @jeremyredhead

**Comment by Jermolene** [comment]
@saqimtiaz I think the CLA bot didn't work correctly for this PR

**Comment by Leilei332** [comment]
Looks like the action for CLA bot is skipped when PR points to the `tiddlywiki-com` branch.

**Comment by saqimtiaz** [comment]
@Jermolene @Leilei332 the CLA bot will not work correctly for PRs against any branch that was created before the `.github/workflows/cla-check.yml` was created.

I suggest merging the path `.github` from master into the `tiddlywiki-com` branch and any other actively developed branch.

From the command line that looks like this for merging into `tiddlywiki-com` branch:
```
git checkout tiddlywiki-com
git checkout master -- .github/
git add .github/ 
git commit -m "Merging workflow updates from master"

```

**Comment by Jermolene** [comment]
Thanks @saqimtiaz I've merged `.github/` in 459cae2817b74849d667d650442dbafabc2d9484

**Pull request merged**
