### PR TITLE
Missing tiddler cascade - To extend the "missing tiddler hint" in the missing tiddler body

### PR DESCRIPTION
**Pull request by pmario**
Many users create links in a tiddler and then click the missing link to create the new tiddlers. 

This workflow works well, if users use `text/vnd.tiddlywiki` type tiddlers. 

But if users mainly work with eg: `text/markdown` the mechanism fails, since the default buttons shown in the tiddler body and tiddler toolbar will create tiddlers with an **empty type field**. 

See: https://talk.tiddlywiki.org/t/how-do-i-make-the-click-edit-to-create-button-make-a-markdown-tiddler/436
See: https://groups.google.com/g/tiddlywiki/c/HtkGP4M1P8M/m/QMhmMXCiCAAJ
see: https://github.com/Jermolene/TiddlyWiki5/issues/6342

This PR prepares the UI to use a "missing tiddler cascade" so plugin authors and core plugins are more flexible to create an improved "Missing Tiddler Workflow". 

This PR doesn't change the default UI or the default workflow as it exists at the moment. It only creates a new "Missing Tiddler Cascade" which plugin authors can use to hook into. 

There will be a second PR, with a proposal, how this  new cascade can be used to improve the core markdown plugin.

The extended Cascase Info will look like this:
missing-tiddler-body-01

and

missing-tiddler-body-02

### CODE REVIEW

**Comment by pmario** [comment]
.

**Comment by Jermolene** [comment]
Thanks @pmario – if the markdown plugin needs to add its own missing tiddler template, surely it could just insert a new rule in the view template body cascade immediately before $:/config/ViewTemplateBodyFilters/default such as `[is[missing]then[$:/plugins/markdown/missingtiddler]]`?

The other way of approaching the original goal might be to introduce segments into the default $:/core/ui/ViewTemplate/body/default template using a tag such as $:/tags/MissingTiddlerSegment. That way, any amount of plugins can add their own custom UI.

**Comment by pmario** [comment]
Just a note. Related to: https://talk.tiddlywiki.org/t/i-overcame-a-hurdle-choose-from-custom-new-tiddler-buttons-when-opening-a-missing-link/4799

**Comment by pmario** [comment]
markdown plugin needs to handle this one

**Pull request closed without merging**
