### PR TITLE
Replace Deprecated renderTiddler with render command 

### PR DESCRIPTION
**Pull request by kookma**
Tiddlers updated:
- How to build a TiddlyWiki5 from individual tiddlers
- Using TiddlyWiki on Node.js
-  tiddlywiki.info Files
- ExternalImages

### CODE REVIEW

**Comment by Leilei332** [comment]
I think we had better replace savetiddler and savetiddlers command with save command too.

**Comment by kookma** [comment]
> I think we had better replace savetiddler and savetiddlers command with save command too.

That's true! I thought to change one by one.
@Jermolene 
Should I replace all deprecated command at once or you accept this PR and then the next one (replacing savetiddler)?

**Comment by Jermolene** [comment]
> That's true! I thought to change one by one. @Jermolene Should I replace all deprecated command at once or you accept this PR and then the next one (replacing savetiddler)?

Thanks @kookma I'm happy to merge things piecemeal or in bigger PRs, whatever works best for you

**Comment by kookma** [comment]
> I think we had better replace savetiddler and savetiddlers command with save command too.

Done. See https://github.com/TiddlyWiki/TiddlyWiki5/pull/8710

**Pull request merged**
