### PR TITLE
Bidirectional text improvements

### PR DESCRIPTION
**Pull request by Jermolene**
TiddlyWiki's language plugin mechanism includes a primitive mechanism for setting the HTML 5 "dir" attribute on the document body to "RTL", thus switching the direction of the user interface. This mechanism is used by languages such as Farsi and Hebrew.

Some of the issues with the current approach is that it is hard to work with tiddlers that have a different directionality to the main interface. For example, the document direction is "LTR" when using the default "en-GB" language plugin, but pasting (say) Farsi into the title, tags, or text fields of a tiddler doesn't switch direction to "RTL".

Prompted by [discussions](https://github.com/Jermolene/TiddlyWiki5/issues/2976#issuecomment-609932541) with @kookma, this experimental PR explores two separate mechanisms that help when working with text of a different directionality than the main interface.

The first is a new `\dir rtl` pragma that can be used at the top of a tiddler to specify that it should be rendered as RTL. This setting is respected if the tiddler content is transcluded elsewhere.

(A shortcoming at present is that the `\dir` pragma must be used after any `\define` pragmas if those macro definitions are to be imported elsewhere with the `\import' pragma).

The second change in this PR is support for a new $:/config/DefaultTextDirection hidden setting. It can be set to "rtl", "ltr" or "auto". It sets the "dir" attribute on several different parts of the view template and edit template.

The interesting thing is the setting "auto", part of the HTML 5 spec. It applies a simple heuristic to detect the appropriate direction for a fragment of text. The default value of $:/config/DefaultTextDirection is "auto". With this setting in place it becomes possible to paste fragments of RTL text into titles, tags, or text fields, and have things work as expected.

(A shortcoming that won't be going away is that the CodeMirror engine doesn't support "auto", just the explicit "RTL" and "LTR" settings. So I think we'll have to handle that entirely differently.

The change that I haven't explored here is adding a "_direction" field on individual tiddlers. That would work much better with the CodeMirror editor, but the disadvantage is that transclusion wouldn't respect the setting.

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @kookma here's a build for you to experiment with: 
[index.html.zip](https://github.com/Jermolene/TiddlyWiki5/files/4445544/index.html.zip)

**Comment by kookma** [comment]
Hi @Jermolene,
I send my first part of comments

For the test cases, I disabled the CodeMirror plugin, so the below results are only for standard Tiddlywiki editor.

I. auto mode

1. **Title** field respects RTL or LTR text, It automatically switch the direction when one starts typing English/Persian (Frasi, Arabic,Hebrew) or paste such texts
2. The **Text** field does not respect the auto direction in EDIT mode! I assume you have not set it to auto like Title. Typing Persian is quite difficult in this state, needs to switch r-t-l
2. The **Text** field and **Title field DO respect the auto direction in VIEW mode! So the correctly render both Persian and English texts


II. Use \dir pragma
1. putting \dir rtl  causes the rendered text in VIEW mode displayed from right-to-left. BUT editor still remains in LTR so, typing Persian is quite difficult in this state, needs to switch r-t-l


III. Use _direction field
1. The setting _direction field to rtl seems has no effect in EDIT mode nore in VIEW mode.


I send my feedback in transclusion in a separate post!

My understanding at first sight:
- The auto seems the best up to now, if editor also respect the auto mode
- It is important to be able to type from right-to-left in tiddler body (text field) in the EDIT mode which is not possible now!

**Comment by Jermolene** [comment]
Thanks @kookma 

> 2. The **Text** field does not respect the auto direction in EDIT mode! I assume you have not set it to auto like Title. Typing Persian is quite difficult in this state, needs to switch r-t-l

It works for me; as soon as I paste Farsi into the text box of a new tiddler it switches to RTL:

image

> 1. putting \dir rtl  causes the rendered text in VIEW mode displayed from right-to-left. BUT editor still remains in LTR so, typing Persian is quite difficult in this state, needs to switch r-t-l

Yes, I think it's most useful in combination with the other techniques when one wants to override the HTML 5 "auto" setting.

> 1. The setting _direction field to rtl seems has no effect in EDIT mode nore in VIEW mode.

No, I did NOT include that change (sorry, I worded it clumsily in the original post!).

> - The auto seems the best up to now, if editor also respect the auto mode

Yes, it seems quite hopeful to me.

> - It is important to be able to type from right-to-left in tiddler body (text field) in the EDIT mode which is not possible now!

Hopefully we'll get that working for you.

**Comment by kookma** [comment]
@Jermolene 
The system I am testing is: 

- Windows 10 latest updated (1909)
- Firefox 75
-Chrome 80.0.3987
-Edge Chromium 83.0.467 

1. I tested again and auto switch of RTL/LTR
- Chrome works great
- Edge Chromium works great
- Firefox: does not switch the direction !!

**Comment by Jermolene** [comment]
Thanks @kookma the Firefox issue should be fixed now. Here's another ZIP.

[a58524611.zip](https://github.com/Jermolene/TiddlyWiki5/files/4446584/a58524611.zip)

**Comment by kookma** [comment]
@Jermolene 
The issue of auto-detect direction with Firefox 75 (latest release) ha gone! I will update you with comments on more testing RTL feature soon

**Comment by kookma** [comment]
Hi @Jermolene , These are some more tests on editing/displaying tiddlers in RTL/LTR direction.

System of tests:
- Windows 10, Firefox 75, Chrome 80.0.xxx, Edge Chromium 84.0.xxx
- Experimental TW `a58524611.zip` from https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-610571020 above


**A. Edit Mode**
- [x] The auto-detect direction works on all browsers the same
- [x] By default cursor blinks on the left 
- [x] Start typing Persian (here this word is used for a right-to-left text like Persian, Hebrew, Arabic,...) or pasting Persian automatically switch direction to right! This is amazing
- [ ] Starting a tiddler with Persian switch direction to RTL, on press Enter and go to the next line cursor blinks on the left! Still one expects to be on the right because, only Enter is pressed and no English word is entered! This is not a big deal and I myself like it because I use a lot of scripts in my tiddlers!
- [x] As TW scripts are in English, so one should be able to enter English scripts (TW scripts, or wikitext) in an RTL tiddler, now TW supports this, so in the middle of an RTL tiddler, if I need to write like (<$list filter="[prefix[پارسی]]"> TW let me to write from left-to-right and enter my script very easily ... ( a lovely feature)
- [x] All spacial characters in English are respected in RTL so I can use headings (`!`) , lists (`*`, `#`) without problem

**B. Rendering and View Mode**
- [x] TW renders, displays tiddler from left-to-right or right-to-left if **the first line** starts with English or Persian respectively
- [ ] If an RTL tiddler, the one starts with Persian contains English sentences, they will be displayed from right-to-left
- [ ] If an LTR tiddler, the one starts with English contains Persian sentences, they will be displayed from right-to-left
- [x] The output of wikitext like below code respects the tiddler direction. So, below code in RTL tiddler shows result in RTL
```
<$list filter="[prefix[آزمون]]">

</$list>
```
- [x] The mixed filter means wikitext contains Persian works great. For example this filter in Advanced search `[prefix[آزمون]]` works with correct results
- [x] Drag and drop of RTL tiddlers with Persian or English Title works great
- [x] Testing some other filters like search works great and one can see correct results for both LTR and RTL tiddlers


**Conclusions of this part**
 - TW supports BiDi  in Edit mode and lets to not only have a tiddler in English (LTR) or Persian (RTL) it lets to have tiddlers of mixed of these texts (both English and Persian)
- TW only supports one direction for rendering or displaying, so it respects an RTL tiddler to display it from right to left, or an LTR tiddler to render or display it from left-to-right BUT, it does not support BiDi in View mode (e.g. the part in English in LTR and the part in Persian in RTL)
 - To address the left-to-right text  in RTL tiddler or vice versa I force TW to display that portion of text in correct direction by wrapping that part in a `div` with proper class, for example displaying a paragraph in English in an RTL tiddler uses the below class

```
.force-ltr{
  direction:ltr;
  unicode-bidi: bidi-override;
}
```

**Comment by kookma** [comment]
More tests on RTL

System of tests:
- Windows 10, Firefox 75, Chrome 80.0.xxx, Edge Chromium 84.0.xxx
- Experimental TW `a58524611.zip` from https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-610571020 above


**This test does not cover all UI elements**

---

- [ ] Setting Username to a Persian word makes the whole tiddler subtitle displayed from right to left, no matter tiddler is English or Persian
- [ ] Setting Username to an English word makes the whole tiddler subtitle displayed from left to right, no matter tiddler is English or Persian
- [x] Using Persian tags, makes tags pill to be displayed from right to left. Adding only one English tag display tags pill from left to right! May be it is better to have a control on this
- [x] Typing Persian word in title automatically switch the direction in edit mode
- [ ] Persian title is displayed from right-to-left and it causes viewtoolbar buttons are displayed from right-to-left while this is expected, but the order of buttons are different for English and Persian title
- [x] The first letter (word) in Title determine the direction of title both in Edit/View mode
- [ ] Site title and site subtitle, always are displayed from left-to-right no matter title/subtitle are in Persian or English. 

**Links and Filters**

- [x] links to RTL tiddler works great in all tiddlers. So a like like [[آزمون]] is valid and works
- [x] Using Persian in wikitext works! Only simple tests have been done mostly in filters
- [x] Using Persian words in widgets works fine like `<$link to="محمد">Hi </$link>` needs more tests for other widgets


** Transclusion **
- [x] Transclusion using `{{tiddler name}}` for Persian tiddler works
- [ ] Transclusion DOES follow the direction of host tiddler not source tiddler. This is true for transcluding both RTL and LTR tiddlers.
- [ ] Transclusion using `<$transclude tiddler="آزمون-۱" field=text mode="block">` is like above
- [x] If the `<$transclude tiddler="آزمون-۱" field=text mode="block">` is used as the first line of tiddler, the tiddler will be RTL one and this is good!
- [x] field name cannot be in Persian, but transclusing like `{{آزمون-۱!!f1}}` works!!
- [x] Transclusing fields with Persian values work fine!

@Jermolene 
While we need to use this trail edition for more tests, but many features work as expected and this is really great! except BiDi (I mean have both direction in one tiddler) other RTL feature work. I compare TW with RTL support with MS-Word and TW showed a good accomplishment in Edit/View modes.

Please let me know if any other test is required.

**Comment by kookma** [comment]
This is an image of a working Tiddlywiki in Persian testing some plugins!
It has an open source web font (Vazir: https://rastikerdar.github.io/vazir-font/) as embedded woff2. Thanks Tiddlywiki 5.1.22!

It looks lovely! Thank you Jeremy!


Image 027


Question: In MsWord one has ability to set latin font for English and complex font for non-English, is this possible in TW in a simple way?

**Comment by kookma** [comment]
More tests
- [x] all tiidlers tagged with wikitext from https://tiddlywiki.com/prerelease/ were duplicated in RTL Tiddlywiki and except the blockquote and transclusion work as expected
- [ ] transclusion as stated in above post gets its direction from host tiddler.
- [ ] blockquote for RTL text should show right border NOT left border, see below
- [ ] quote has the same issue as blockquote
- [ ] Persian has not CamelCase so, it is not available in RTL Tiddlywiki
- [ ] Info panel is RTL for RTL tiddler and LTR for LTR one. It is good to have control on this


I have created a demo wiki with all above tests

http://kookma.rtl.tiddlyspot.com/


**Suggestion**

- I have solved the issue with quotes and blockquotes by adding the below css to RTL wiki

```
/* adjust the rtl blockquotes */ 
blockquote:dir(rtl) { 
border:none; 
border-right: 5px solid #bbb; 
margin-right: 25px; 
padding-right: 10px; 
}
```

- The temporary remedy for transclusion in my RTL wiki is using  css classes as below

```
/*my mixed class*/

.force-ltr{ direction:ltr; unicode-bidi: bidi-override; }

.force-rtl{ direction:rtl; unicode-bidi: bidi-override; }
```


**Conclusion**

1. It seems the experimental Tiddlywiki with RTL feature works great and passes almost all tests!
2. Developing mixed scripts e.g. a macro where its name is Persian or a transclusion where name is Persian and field is English is difficult! This is not related to Tiddlywiki but relates to html technology. The part of these issues can be seen in commercial software like MS-Word which has a good reputation in BiDi support
3. The layout has not been discussed in these review/comments and I think it is the subject of next phase and I am sure few modifications to $:/themes/tiddlywiki/vanilla/base will resolve the issues

**Comment by abdnh** [comment]
I'm excited to see this in TiddlyWiki. Thank you for your work!
Will this be merged soon?

**Comment by pmario** [comment]
@kookma .. Do you still use it?

Should the tiddler toolbar be on the right or left side? IMO it should be easy to change, with a little "theme" setting in a stylesheet.

eg:

```
.tc-tiddler-frame .tc-tiddler-controls {
    float: left;
}
```

**Comment by kookma** [comment]
> @kookma .. Do you still use it?

Yes, I use it! Thank you for the tip. Unfortunately I cannot update the wiki on tiddlyspot.com, but hopefully will create a GitHub repo with latest change!

@Jermolene  - It would be great if the `rtl` support could be merged into Tiddlywiki or introduced as an official plugin. I am ready to help.

**Comment by kookma** [comment]
> a58524611.zip

Hello @Jermolene 
This is a rather old version. Is it possible to have this bidirectional in progress Tiddlywiki in 5.2.6pre?

I did extensive test here and I think if you have time, we can finalize the bidirectional Tiddlywiki.

**Comment by Jermolene** [comment]
Thanks for the reminder @kookma.

I've updated this PR with the latest changes from the master branch, which means that there is now a Vercel preview which should make thing easier. There's still a bit more cleaning up to do, but it would be helpful to make an updated list of the remaining issues.

**Comment by kookma** [comment]
Much appreciated. I will do some experiment next week and will try to summarize and links other issues related here.
Also I will reread this long thread and will update you with remaining issue!
Thank you @Jermolene

**Comment by kookma** [comment]
Hi Jeremy,
 I did some tests, and the preview works fine. So the same results are valid here with provided preview 5.2.6prerelease

* https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-611088438

I would appreciate to update the preview to current master branch. I will continue my further tests.

I hope we can have bidi support in official release of 5.3.0 or 5.2.x.

**Comment by Jermolene** [comment]
Hi @kookma I've updated this branch from master. The preview should update itself shortly

**Comment by kookma** [comment]
Thank you Jeremy!

**One question**: In the below examples TW works perfectly in edit mode.
If I start a line writing Persian it switches to right and if I start a line writing English, it switches to left. So far so good!

**EDIT Mode**

image
image


**VIEW Mode**

When I save the tiddler, in rendered mode (view mode) TW shows text from Right or Left based on the first line of text!

image
image


**Expected behavior**: The render mode/view mode should keep the same directions you see in edit mode!

Is this because the direction applies to the whole body and not to different paragraphs inside body?

**Comment by DK5** [comment]
Hi @kookma,
The direction attribute should be set to "auto" for each paragraph seperately:
dir = auto

[Amit](https://talk.tiddlywiki.org/t/tw5-change-layout-rtl-ltr-when-editing-tiddler/6765) has managed to figure out a workaround, embedding this code in `$:/core/modules/widgets/reveal.js`:

```
 var paragraphs = document.getElementsByTagName("p");
	for(var i = 0; i < paragraphs.length; i++){
		paragraphs[i].setAttribute("dir","auto");
	}
```

**Comment by kookma** [comment]
Thank you @DK5.

Did you use the preview version here or the TW 5.2.7?
I did not figure out in $:/core/modules/widgets/reveal.js exactly where the proposed workaround should be added.

**Comment by DK5** [comment]
Hey @kookma 
Sorry for not being more specific, the code should be added in `RevealWidget.prototype.refresh`:
```
RevealWidget.prototype.refresh = function(changedTiddlers) {
	var changedAttributes = this.computeAttributes();
	var paragraphs = document.getElementsByTagName("p");
	for(var i = 0; i < paragraphs.length; i++){
		paragraphs[i].setAttribute("dir","auto");
	}		
...
};
```

We have tested it on previous TW versions (I think 5.2.5), also tested now on yours:
image

**Comment by Jermolene** [comment]
Hi @DK5 

>  The direction attribute should be set to "auto" for each paragraph separately:

That's very interesting. I had thought that the `dir` attribute was inherited but evidently not in the way that I was expecting.

I experimented with modifying the wikiparser.js to include the `dir` attribute by changing the return value of `parseBlock` to:

```
	return [{type: "element", tag: "p", attributes: {dir: {type: "string", value: "auto"}}, children: children, start: start, end: end }];

```

It also causes all the tests to fail because of the unexpected new attribute on all paragraphs.

**Comment by kookma** [comment]
> Sorry for not being more specific, the code should be added in `RevealWidget.prototype.refresh`:

No problem. I got it now! Thank you.



> We have tested it on previous TW versions (I think 5.2.5), also tested now on yours:

Also tested with TiddlyWiki 5.3.0pre, It works like a charm! Thank you.
image

**Comment by kookma** [comment]
Hi @pmario 

I have tested the bidirectional feature in the preview provided by @Jermolene (see link above: https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-1518553103)

As I have thoroughly tested before (see also this post: https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-611088438) bidirectional feature works as expected. BUT, I like to have the solution by @DK5 (in https://github.com/Jermolene/TiddlyWiki5/pull/4541#issuecomment-1518632703) merged. The reason is TW does not switch RTL/LTR in view mode automatically!

**Comment by kookma** [comment]
Hi @Jermolene 
> Does it make sense to merge this PR anyhow, without that enhancement?
I think yes. The PR will work except for below issue:

* If a first line of text (tiddler body) is RTL, then the whole tiddler is rendered as RTL
* If a first line of text (tiddler body) is LTR, then the whole tiddler is rendered as RTL
* The desired and correct situation is to render RTL paragraph as RTL and LTR paragraph as LTR not based on first line of text.

All in all, I recommend merging this PR and open another PR/Issue to address this case.

**Comment by Jermolene** [comment]
The new PR with these changes can be found at #7557

**Comment by kookma** [comment]
> Hey @kookma Sorry for not being more specific, the code should be added in `RevealWidget.prototype.refresh`:
> 
> ```
> RevealWidget.prototype.refresh = function(changedTiddlers) {
> 	var changedAttributes = this.computeAttributes();
> 	var paragraphs = document.getElementsByTagName("p");
> 	for(var i = 0; i < paragraphs.length; i++){
> 		paragraphs[i].setAttribute("dir","auto");
> 	}		
> ...
> };
> ```

Hi @DK5 
Have you tested this method on TW 5.3.6? The current bidi version of TW https://github.com/TiddlyWiki/TiddlyWiki5/pull/7557 has one issue, if you start a tiddler with rtl it stays as rtl tiddler, if start with ltr, it keeps all text in rtl. One benefit of your solution is it correctly align text at each paragraph. It paragraph starts with English it stays ltr and if starts with Persian/Arabic/Hebrew, it aligns rtl.

**Comment by Jermolene** [comment]
Hi @kookma I've implemented the fix mentioned in https://github.com/TiddlyWiki/TiddlyWiki5/pull/4541#issuecomment-1518637241 and fixed up the test failures - 182 files were affected!

Please let me know how you get on with the update.

**Comment by kookma** [comment]
> Hi @kookma I've implemented the fix mentioned in [#4541 (comment)](https://github.com/TiddlyWiki/TiddlyWiki5/pull/4541#issuecomment-1518637241) and fixed up the test failures - 182 files were affected!

Thank you @Jermolene!

I did not find a single file html to test. So I did as below

* Updated my local copy of TiddlyWiki 
* Change branch to `new-bidi-improvements`
* Create a test wiki
* Start testing with making new tiddlers

### An issue

* When you create a new tiddler you see an extra `</div>` in edit mode, see below image

image


## Testing with LTR, RTL

### Edit mode (does not work)
I start writing in Persian (Farsi), TW automatically aligns the text from LTR. Wonderful
Then I start a new paragraph by pressing enter twice and start writing in English, TW still writes from right to left, BUT, it should switch to left to right.

image


### View mode, rendered tiddler (works as expected)
In view mode the rendered tiddler now works fine. English text aligned LTR and Persian text aligned RTL
image


## Remarks
* The new-bidi-improvement branch works better than recently BIDI on TW 5.3.7 created by (https://github.com/TiddlyWiki/TiddlyWiki5/pull/7557)
* In view mode everything is fine: English aligns LTR, Persian/Hebrew/Arabic align RTL
* In edit mode, if you start first line of tiddler in English it aligns everything in LTR, if you start with Persian, it aligns everything in RTL.

msedge_img_503_20250128


So, if the issue is the edit mode now!

**Comment by Jermolene** [comment]
Apologies for the confusion @kookma, the updates are in #7557, and the preview is at https://deploy-preview-7557--tiddlywiki-previews.netlify.app/

**Comment by Jermolene** [comment]
Hi @kookma 

> Now, only the issue is in the edit mode to respect the LTR and RTL paragraph.

I think that the HTML `<textarea>` element and hence the core text editor are only able to use a single setting for the entire control. It may conceivably be possible to get something working in CodeMirror.

For that reason, perhaps we should advise users that things will be easier if they use transclusion to build up tiddlers that need to mix RTL and LTR.

**Comment by Jermolene** [comment]
> For that reason, perhaps we should advise users that things will be easier if they use transclusion to build up tiddlers that need to mix RTL and LTR.

And if we do that, we should consider dropping the `dir=auto` on `<p>` tags.

**Comment by kookma** [comment]
> Hi @kookma
> 
> > Now, only the issue is in the edit mode to respect the LTR and RTL paragraph.
> 
> I think that the HTML `<textarea>` element and hence the core text editor are only able to use a single setting for the entire control. It may conceivably be possible to get something working in CodeMirror.
> 
> For that reason, perhaps we should advise users that things will be easier if they use transclusion to build up tiddlers that need to mix RTL and LTR.

Thank you @Jermolene 

Please see below TiddlyWiki both uses @DK5 solutions and they work as exptected.


1.  https://kookma-bidi.tiddlyhost.com/ (version 5.3.0-pre)
2. http://kookma.rtl.tiddlyspot.com/  (old version 5.1.22-prerelease)

Both overwrite the [$:/core/modules/widgets/reveal.js](https://kookma-bidi.tiddlyhost.com/#%24%3A%2Fcore%2Fmodules%2Fwidgets%2Freveal.js) using the @DK5 solutions.

**Comment by kookma** [comment]
Hi @Jermolene 
Would you please address the extra `</div>` in edit mode, see below image:

image


Also, does it mean to use below CSS to address the automatic RTL/LTR in edit mode

```

**Comment by Jermolene** [comment]
Thanks @kookma I've implemented both those fixes in b92636e715b767d6fd5289d4e8dcc75b7594854e

By the way, this conversation would better on #7557 since this PR is closed.

**Comment by kookma** [comment]
Thank you, Jeremy!
Much appreciated!

**Pull request merged**
