### PR TITLE
add startCount to unusedtitle macro, new tests, new docs

### PR DESCRIPTION
**Pull request by pmario**
This PR is a draft, because tests need to be merged first

- #7939

This PR contains: 

- add startCount to unusedtitle macro, 
- new tests, 
- new docs

### CODE REVIEW

**Comment by pmario** [comment]
@Jermolene Can you have a look at

- #7939
- #7940 

So I can make this one are PR?

**Comment by Jermolene** [comment]
Thanks @pmario I've left a comment on #7939, and merged #7940

**Comment by pmario** [comment]
@Jermolene ... These tests should be merged prior to activating this PR:  **add startCount to unusedtitle macro, new tests, new docs #7941**

**Comment by pmario** [comment]
- I did merge "master" into this branch so it is up to date again
- Since https://github.com/Jermolene/TiddlyWiki5/pull/7939 is merged now, this one can be reviewed. 

@Jermolene -- please review

**Comment by pmario** [comment]
@Jermolene -- Did merge master into this branch. Tests old an new are OK

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request merged**
