### PR TITLE
Use colour-picker macro in Tag Manager

### PR DESCRIPTION
**Pull request by Leilei332**
See #8603 .

This require #8605 to display properly.

图片

### CODE REVIEW

**Comment by Jermolene** [comment]
Great thanks @Leilei332

**Comment by kookma** [comment]
@Leilei332 
I have tested the new color picker, and it seems there are _some issues_

**1**. move mouse on left side of color chooser what is that clickable square?
image

**2.** Clicking in the input box of color chooser or the button itself closes the drop down

msedge_img_297_20240916

**Comment by kookma** [comment]
Another issue:
If you set the color of a tag through TagManager using new color macro, it will not correctly be displayed on the tag tiddler.
For example change the color of About tiddler

1. select a color for About
image

2. See the color by editing About tiddler
image

**Comment by Leilei332** [comment]
> 1. move mouse on left side of color chooser what is that clickable square?

This square does have function. After you select a color with the native color or input a valid color in the input field on the left, the square shows the color to be picked. IMO we should update the macro to hide it when the input field is empty.

图片

> 2. Clicking in the input box of color chooser or the button itself closes the drop down

This problem does related to the implementation of the drop down, `tc-popup-keep` should have been added to the class attribute.

> Another issue:
If you set the color of a tag through TagManager using new color macro, it will not correctly be displayed on the tag tiddler.
For example change the color of About tiddler

This is because the native HTML color picker does not support [CSS color keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/named-color) , so we had better create a [Field Editor Cascade](https://tiddlywiki.com/prerelease/#Field%20Editor%20Cascade) to input text with a colour-picker macro dropdown.

**Comment by kookma** [comment]
> This square does have function. After you select a color with the native color or input a valid color in the input field on the left, the square shows the color and you can click it to pick the color. IMO we should update the macro to hide it when the input field is empty.

This does not work on Edge or Chrome. Only works on Firefox. I stiil expect to have the dropdown open to see what user has selected.

**Comment by Leilei332** [comment]
> > This square does have function. After you select a color with the native color or input a valid color in the input field on the left, the square shows the color and you can click it to pick the color. IMO we should update the macro to hide it when the input field is empty.
> 
> This does not work on Edge or Chrome. Only works on Firefox. I expect to have the dropdown open to see what user has selected.

Actually it does work on Chrome 128 (After I added `tc-popup-keep` to the class attribute reveal widget). I think this problem is related to the second one:

动画

> I expect to have the dropdown open to see what user has selected.

Colour-picker macro does not support displaying selected color, but the input field below displays color in `$:/config/ColourPicker/New`. IMO we can create an action for the button to set the content of this tiddler to the colour of the tag.

**Comment by pmario** [comment]
@kookma -- you should create a new issue, that links to this one. Merged PRs are listed as "closed". So creating a new issue is the way to go.

**Pull request merged**
