### PR TITLE
Add keyboard shortcut option for menubar search

### PR DESCRIPTION
**Pull request by michaeljmcd**
Adds tiddlers to give an option to set a keyboard shortcut for menubar search apart from the one that exists for sidebar search, as discussed at https://talk.tiddlywiki.org/t/keyboard-shortcut-for-menu-bar-search/10089

### CODE REVIEW

**Comment by Jermolene** [comment]
Hi @michaeljmcd many thanks for your contribution – this is a worthwhile improvement. 

With apologies for the bureaucracy, please could you prepare a separate PR to the 'tiddlywiki-com' branch with your signature for the Contributor License Agreement (see [contributing.md](https://github.com/Jermolene/TiddlyWiki5/blob/master/contributing.md)).

**Comment by michaeljmcd** [comment]
Makes sense. Created a PR to sign the CLA: https://github.com/Jermolene/TiddlyWiki5/pull/8361

**Comment by Jermolene** [comment]
Thank you @michaeljmcd – I'll merge this once [v5.3.5 is released](https://github.com/Jermolene/TiddlyWiki5/issues/8331)

**Comment by Jermolene** [comment]
Thanks @michaeljmcd

**Pull request merged**
