### PR TITLE
#8854 fix acl error in anon mode

### LINKED ISSUE #8854: MWS: HTTP 403 error clicking on ACL button in anonymous mode
Steps to reproduce:

1. Start with a fresh install of MWS
2. Run `npm install` and `npm start`
3. Visit http://127.0.0.1:8080/ in a browser
4. Click the padlock icon next to the **dev-docs** wiki
5. Observe the HTTP 403 error at the path http://127.0.0.1:8080/admin/acl/dev-docs/dev

cc @webplusai

### PR DESCRIPTION
**Pull request by webplusai**
fixes #8854

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @webplusai

**Comment by Jermolene** [comment]
Hi @webplusai tests are failing at the moment

**Comment by webplusai** [comment]
@Jermolene test issues are fixed.

**Comment by Jermolene** [comment]
Thanks @webplusai

**Pull request merged**
