### PR TITLE
Add view template for normal compound tiddlers

### PR DESCRIPTION
**Pull request by Leilei332**
This PR implements a basic view template for tiddlers without the `$:/tags/wiki-test-spec` but has type `text/vnd.tiddlywiki-multiple`.

It has a tab showing its tiddlers, a table showing the tiddlers' fields and displays its rendered text in the bottom.

图片

### CODE REVIEW

**Comment by Jermolene** [comment]
Thank you @Leilei332 @pmario. The idea of a custom view template for compound tiddlers does make a lot of sense.

To @pmario's point about the value of showing the plain text, one issue is that there can be fields in the compound tiddler that affect how the text is interpreted (eg the new field for importing other compound tiddlers).

Given the complexity of the inheritance arrangements, I think there is real value in being able to see exactly what tiddlers are derived from a given compound tiddler.

I think the tabbed layout is problematic because it requires too much clicking to get an overview.

I prefer the idea of a tabbed display. The default tab would be labelled "Tiddlers" and contain a listing of the tiddlers derived from the compound tiddler. The second tab would be labelled "Source" and would contain the text of the tiddler, but with a table at the top with the relevant fields pulled out.

One reservation about that approach is that it would involve a handful of new translatable strings, perhaps adding disproportionately to the size of the core.

**Comment by Jermolene** [comment]
Hi @Leilei332 we need to decide how to proceed with this. I am not against the idea of a friendly template, my only concern is that we shouldn't hide information that is present in the raw text.

**Comment by Leilei332** [comment]
Actually I prefer `text/plain` view now, since the format is readable in plain text.

**Comment by Jermolene** [comment]
Hi @Leilei332 I agree. I do still wonder whether it would be worth providing a way to see the entire resulting payload (including imports), but that would be a different thing than this PR.

**Pull request closed without merging**
