### PR TITLE
feat: allow tags have its ViewTemplate tag and cascade

### PR DESCRIPTION
**Pull request by linonetwo**
Title and subtitle and body all have their ViewTemplate tag and cascade, now it's tag's turn.

I will need this to build https://saqimtiaz.github.io/sq-tw/sandbox.html#%24%3A%2Fcore%2Fui%2FViewTemplate%2Ftags that is not shadowing anything.

@pmario @saqimtiaz

### CODE REVIEW

**Comment by linonetwo** [comment]
Example usage [tiddlers.json](https://github.com/user-attachments/files/16445931/tiddlers.json)

图片

**Comment by Jermolene** [comment]
Thanks @linonetwo I think that the "subtitle" segment is now the only substantive view template segment that does not have a cascade. I think it would be worth giving it a cascade too, in this same PR.

We also need to add the new cascades to the control panel.

**Comment by linonetwo** [comment]
图片

@Jermolene Updated, with some i18n

**Comment by Jermolene** [comment]
Thanks @linonetwo

**Comment by kookma** [comment]
@linonetwo 
I highly recommend to follow the same philosophy among Cascades.

So, I propose to add the default template for `View Template Tags`.

For example, see `View Templates Fields`, it is like belo:

image


BUT for `View Template Tags`, it is empty:

image


* In other words, the current Tags shall be displayed through a default template
* Users can utilize cascades by employing `list-before` fields to override the default template.

**Comment by linonetwo** [comment]
@kookma I copied the code from $:/core/ui/ViewTemplate/body

@Jermolene 
Should I delete the ` :and[!is[blank]else[$:/core/ui/ViewTemplate/body/default]]` fallback from `$:/core/ui/ViewTemplate/body` too? Or is this a defensive programming and is left intended?

**Comment by linonetwo** [comment]
截屏2024-08-02 14 27 57

I'm confused, why it takes effect without adding `list-before: $:/config/ViewTemplateTagsFilters/default`?

**Comment by linonetwo** [comment]
Updated in https://github.com/TiddlyWiki/TiddlyWiki5/pull/8470

**Comment by Jermolene** [comment]
Thanks @kookma – I think it is important to match the existing cascades, which means shipping an explicit cascade entry rather than relying on the fallback.

> @Jermolene Should I delete the ` :and[!is[blank]else[$:/core/ui/ViewTemplate/body/default]]` fallback from `$:/core/ui/ViewTemplate/body` too? Or is this a defensive programming and is left intended?

That's correct.

**Pull request merged**
