### PR TITLE
MWS - Make eslint happy to allow inner function declarations for tests

### PR DESCRIPTION
**Pull request by pmario**
This PR will allow inner function definitions eg:

```
if ($tw.node) {
  function test() {}
}
```

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @pmario does the core use inner functions in that style? I would have expected JS hoisting to pull the function definition outside of the conditional in any case.

**Comment by pmario** [comment]
With my VSCode it looks like this, which makes the code unreadable.

The offending code is `if($tw.node)` and the a `function xx()` below. 
If the PR is added VSCode is happy. 

image

**Comment by Jermolene** [comment]
Thanks @pmario that makes it clearer that we should fix that JS file, and leave the ESlint settings alone

**Comment by pmario** [comment]
So I'll close this PR

**Pull request closed without merging**
