### PR TITLE
Testing StackBlitz

### PR DESCRIPTION
**Pull request by Jermolene**
This trivial PR is to enable us to evaluate integration with https://stackblitz.com/

### CODE REVIEW

**Comment by pmario** [comment]
hmm, I did start the different links several times. It worked the first time, then it starts to completely fail. I did close the tabs and did click the links provided here. -> fails. 

What is it supposed to do. For me it starts an ultra slow development environment.

**Comment by Jermolene** [comment]
> hmm, I did start the different links several times. It worked the first time, then it starts to completely fail. I did close the tabs and did click the links provided here. -> fails.

It works great on my laptop, but I can't get it to work on my phone or iPad.
 
image

> What is it supposed to do. For me it starts an ultra slow development environment.

It is an alternative to Vercel that @btheado mentioned - see https://github.com/TiddlyWiki/TiddlyWiki5/issues/8420#issuecomment-2284577751

When it works, the advantage of Stackblitz is that it makes it possible to review Node.js PRs without installing anything locally. The old Vercel preview builds were not helpful for these kinds of PRs.

**Comment by linonetwo** [comment]
It works on my Firefox.

I did encountered some failure, but I think it might related to cache or network issue. At least it works today.

**Comment by pmario** [comment]
>...  I think it might related to cache ...

Yes. If I do clear the browser cache and start anew, it seemed to work. But it takes several minutes😞 -- 

The advantage is, that it automatically restarts the server after a code change. 
The disadvantage is, that the editor speed in the browser is too slow for me personally. (or my computer is too old)

**Comment by linonetwo** [comment]
Although they advertise in https://blog.stackblitz.com/posts/introducing-webcontainers/

> Boot a Node.js project in your browser in milliseconds (don’t blink!):

But even my Mac with Intel Core i9 will take 5s+ to boot TW, and CPU temperature will gets to 90°C . Anyway I think stackblitz works well if 

1. make sure new tab is at foreground, (this means wait it at foreground for 5-20s...)
2. cool down the CPU
3. clear cache if sometimes we mistackly run it on background and it throws error

**Comment by Jermolene** [comment]
I've disabled StackBlitz for the following reasons:

* It puts too much load on the users browser
* It doesn't work on mobile devices
* It frequently crashes on desktop devices

**Pull request closed without merging**
