### PR TITLE
Add drag-and-drop handling for export buttons

### LINKED ISSUE #8497: [IDEA] add drag-and-drop handling to the $:/AdvancedSearch Filter "export" button
Sometimes I want to export/import a bunch of tiddlers from one TiddlyWiki to another, using the $:/AdvancedSearch > Filter tab, but I don't want to download a JSON file and then drag it to the other TiddlyWiki.

Instead, I just want to drag-and-drop all the matching titles into the other TiddlyWiki.

This can be easily done by making a VERY small change in `$:/core/macros/export`:

Change this:
`<$button popup=<<qualify "$:/state/popup/export">> tooltip=<<hint>> aria-label=<<caption>> class=<<tv-config-toolbar-class>> selectedClass="tc-selected">`
to
`<$button popup=<<qualify "$:/state/popup/export">> tooltip=<<hint>> aria-label=<<caption>> class=<<tv-config-toolbar-class>> selectedClass="tc-selected" dragFilter=<<__exportFilter__>>>`

(i.e., adding `dragFilter=<<__exportFilter__>>` to the `$button`.

With this small change, the export button can now be dragged directly onto another TiddlyWiki to initiate an interactive $:/Import of all the matched tiddlers.

I already have this functionality in the "export" button in https://tiddlytools.com/#TiddlyTools%2FSearch%2FFilters, but it would be convenient if this was also a core usability feature enhancement, so that the same drag-and-drop handling is available from ANY TiddlyWiki, without needing to use my custom search.

### PR DESCRIPTION
**Pull request by Leilei332**
This PR closes #8497 .

Add drag-and-drop handling for all export buttons.

### CODE REVIEW

**Comment by pmario** [comment]
See my comment at: https://github.com/TiddlyWiki/TiddlyWiki5/issues/8497#issuecomment-2277283396

**Comment by Leilei332** [comment]
It is strange that the variable `exportButtonFilename` defined in `$:/core/marcos/export` is neither used by the exporter (it appeared only once in the file) nor used by other system macros (searching `exportButtonFilename` only have 1 result). It isn't documented in tiddlywiki.com too.

图片

图片

**Comment by pmario** [comment]
That's my take on how to make the existing code human readable: https://github.com/TiddlyWiki/TiddlyWiki5/pull/8504/files?diff=unified&w=0

It does **not** contain any new functionality

**Comment by Leilei332** [comment]
Since #8513 has been merged, this one has to be closed.

**Comment by Jermolene** [comment]
Hi @Leilei332 I am still interested in the functionality of this PR, do you plan to make a new one?

I think it might be helpful if we introduced an icon or other decoration that we could use consistently to indicate that something is draggable. (We would then have the question of whether to retrospectively do the same to tag pills - which can of course already carry an icon).

**Comment by Leilei332** [comment]
I did plan to make new PR after #8513 is merged, and I think we can convert it to a procedure if possible. But I'm afraid that I can't set aside some time to work on a new PR since I'm busy at present.

> I think it might be helpful if we introduced an icon or other decoration that we could use consistently to indicate that something is draggable. (We would then have the question of whether to retrospectively do the same to tag pills - which can of course already carry an icon).

IMO it's better to keep the UI simple. I think we can document it in tiddlywiki.com instead of adding more UI elements (if we add it, it should not hold to much space. It should also be less distractive)

**Comment by Jermolene** [comment]
Thanks @Leilei332

**Pull request closed without merging**
