### PR TITLE
add tag-tiddler to tag-pill drag & drop import, add hidden setting for TagPillDragFilter

### PR DESCRIPTION
**Pull request by pmario**
This PR fixes: #8181

- #8181

- It adds the tag-tiddler to tag-pill drag & drop import. 
- It adds a hidden setting for TagPillDragFilter
- It adds some relatively detailed docs about the hidden setting, what to do to revert to the "old" behaviour. 
  - The old behaviour was buggy, since it also exports "Draft tiddlers" even if they are not shown in the tag-dropdown.

### CODE REVIEW

**Comment by pmario** [comment]
@Jermolene -- bump

**Comment by Jermolene** [comment]
Hi @pmario as I mentioned [here](https://github.com/TiddlyWiki/TiddlyWiki5/issues/8181#issuecomment-2098977770), on balance I think that we should not change the default behaviour.

**Comment by pmario** [comment]
@Jermolene -- I did change the default, so it dos **not** include the tag tiddler itself. Also updated the docs.

**Comment by Jermolene** [comment]
Thanks @pmario

By the way, it might be useful to make a plugin that contains a UI for the hidden settings. The motivation for keeping these settings hidden is generally to avoid bloating the core with the relevant language strings, so putting the UI in a plugin would be reasonable.

**Pull request merged**
