### PR TITLE
Make Excision Available for Markdown

### PR DESCRIPTION
**Pull request by michaeljmcd**
Markdown as an option in the criteria to use excision and by making the excise operation reuse the type of the tiddler being excised.

In current state, the excision button automatically hides for Markdown tiddlers. If this is manually overridden, then excising from one Markdown tiddler will create a tiddler without a type, which will not render as expected.

### CODE REVIEW

**Comment by Leilei332** [comment]
There exists a small problem that the excise button makes links in wikitext syntax for markdown tiddlers. IMO they should make links in markdown syntax.

**Comment by michaeljmcd** [comment]
Is your thought to generate links in the format below?

```
[my link](<#A Relevant Tiddler>)
```

Another consideration is that the Markdown plugin supports both traditional Markdown link syntax and wiki format (c.f. the pretty link pragma in https://tiddlywiki.com/plugins/tiddlywiki/markdown/#%24%3A%2Fplugins%2Ftiddlywiki%2Fmarkdown). I think wiki links are even enabled by default.

Another option is to check `$:/config/markdown/renderWikiTextPragma` for `prettylink` to decide which syntax to use for Markdown.

**Comment by michaeljmcd** [comment]
@Leilei332 - I pushed an updated version to https://github.com/michaeljmcd/TiddlyWiki5/tree/markdown-excise2 that uses wiki links if the markdown pragma is set and falls back on Markdown style links otherwise. I'll merge it into this branch if this is preferred.

**Comment by Leilei332** [comment]
IMO there is no need to detect enabled wikitext pragma. We can let links created by excision in markdown tiddlers use the markdown syntax regardless of the wikitext pragma.

**Comment by michaeljmcd** [comment]
@saqimtiaz thanks for the reminder, I've made the change to use Markdown syntax for links inserted while excising and resolved merge conflicts.

**Comment by Jermolene** [comment]
Great thanks @michaeljmcd

**Pull request merged**
