### PR TITLE
Signing CLA

### PR DESCRIPTION
**Pull request by Jdigio0213**
Signing CLA

---
<small>Submitted using https://saqimtiaz.github.io/tw5-docs-pr-maker/.</small>

### CODE REVIEW

**Comment by pmario** [comment]
@Jermolene -- This seems to be a fake account. IMO should be blocked

**Comment by Jermolene** [comment]
Hi @pmario I don't see any evidence of that. I think the multiple submissions is an issue with the PR maker.

**Comment by pmario** [comment]
There has **not** been a single interaction that made sense, except some cloned repositories. -- That's it. 

- https://github.com/OGKevin/obsidian-kobo-highlights-import/issues/41 .. This is an empty issue at a random repo.
- https://github.com/Jdigio0213?tab=overview&from=2024-08-01&to=2024-08-30
- As I looked at it, there where 5 repositories pinned at the users home-page
- Now there is only tiddlywiki -- For me the overall behaviour is suspicious at least.

It's OK if you give the benefit of the doubt, but I'm really interested if there is any answer to your [request for feedback](https://github.com/TiddlyWiki/TiddlyWiki5/pull/8565#issuecomment-2320486091)

Just to be safe, I personally would **lock** all the closed PRs to avoid future comments

**Comment by Jermolene** [comment]
Thanks @pmario let's leave things for the moment and review in a day or two.

**Pull request closed without merging**
