### PR TITLE
Fix whitespace in all plugins for v5.3.6

### PR DESCRIPTION
**Pull request by pmario**
Fix whitespace in all plugins for v5.3.6

- This PR changes whitespace only for our current plugin directory. 
- I did check all plugins for whitespace problems.

### CODE REVIEW

**Comment by pmario** [comment]
@Jermolene - I did update the OP with: 

- This PR changes whitespace only for our current plugin directory. 
- I did check all plugins for whitespace problems.

**Comment by pmario** [comment]
@Jermolene -- I think we should merge this one now, since v5.3.5 is active now. It only deals with redundant whitespace

**Comment by pmario** [comment]
@Jermolene -- bump

**Comment by pmario** [comment]
@Jermolene -- please review

**Comment by Jermolene** [comment]
Thanks @pmario

**Pull request merged**
