### PR TITLE
Improve View Widget refreshing

### PR DESCRIPTION
**Pull request by BurningTreeC**
Please test.
This is basically the same as #8135 but with date template handling

### CODE REVIEW

**Comment by pmario** [comment]
@BurningTreeC please have a look at my comment: https://github.com/TiddlyWiki/TiddlyWiki5/pull/8135#issuecomment-2371133764

**Comment by pmario** [comment]
I will create a PR to your branch with all the tests I did already create. There may be some missing.

**Comment by pmario** [comment]
@BurningTreeC -- See: https://github.com/BurningTreeC/TiddlyWiki5/pull/4

**Comment by pmario** [comment]
I think the function `View.prototype.getValue = function(format) {`  can be refined, since `self.getValue(format)` is already able to format the output string. 

IMO `return $tw.utils.formatDateString(value,format);` **is not needed**

**Comment by BurningTreeC** [comment]
> @BurningTreeC please have a look at my comment: [#8135 (comment)](https://github.com/TiddlyWiki/TiddlyWiki5/pull/8135#issuecomment-2371133764)
> 
> ```
> /*
> Initialise date mehods
> */
> ViewWidget.prototype.initialiseDateView = function(View) {
> 	var self = this;
> 	View.prototype.getValue = function(format) {
> 		format = format || self.viewTemplate || "YYYY MM DD 0hh:0mm";  // NEW
> 		var value = $tw.utils.parseDate(self.getValue(format)); // NEW
> 		if(value && $tw.utils.isDate(value) && value.toString() !== "Invalid Date") {
> 			return $tw.utils.formatDateString(value,format);
> 		} else {
> 			return "";
> 		}
> 	};
> 	return View;
> };
> ```
> 
> I think the `format = format || ...` needs to stay, otherwise calling the function from JS will not work anymore.

Hi @pmario , no I don't think it has to stay. It's perfectly fine like I do it here in this PR if I don't get it totally wrong.
Or what do you mean by "calling the function from JS"?
I'm calling the function from JS here and it works...

**Comment by pmario** [comment]
I think a found a "road-block". 

Have a look at master: https://github.com/TiddlyWiki/TiddlyWiki5/blob/678c272979d2ca4813bca7bbb07ce45d82f9e7c2/core/modules/widgets/view.js#L103

The current view-widget base-class `.getValue` has a function signature like this `.getValue(options)` 

You need to keep that signature for all `.getValue(options)` functions in your code. Otherwise the change will not be backwards compatible for **plugin authors**, that use the [Widget-subclassing mechanism](https://tiddlywiki.com/dev/#WidgetSubclassingMechanism).

IMO the same thing is true for all other `.prototype.xx()` functions, that already have a parameter. IMO you need to to keep the existing signature in tact **and add** an `(existing, options)` parameter if you need to pass on new params.

If there is already an `xx(options)` parameter, you can add your new keys there in a compatible way.

So the function signatures do not change. -- I'll have to have a closer look at the code again.

**Pull request closed without merging**
