### PR TITLE
Add Document for New Shortcutkey to Open Control Panel

### PR DESCRIPTION
**Pull request by kookma**
This PR adds documents for new feature added in https://github.com/TiddlyWiki/TiddlyWiki5/pull/8439

### CODE REVIEW

**Comment by pmario** [comment]
That's the documentation only. IMO you forgot to push the config tiddlers.

As a starting point you can use the advanced search configuration and change it accordingly:
https://github.com/TiddlyWiki/TiddlyWiki5/blob/master/core/ui/KeyboardShortcuts/advanced-search.tid

Then shortcut config tiddler

grafik

The $:/config/ShortcutInfo multids needs to be updated: https://github.com/TiddlyWiki/TiddlyWiki5/blob/master/core/wiki/config/ShortcutInfo.multids with a new Hint text. 

We can use the existing ``$:/language/Buttons/ControlPanel/Hint`

I think that's it. Also see: https://tiddlywiki.com/#How%20to%20create%20keyboard%20shortcuts

**Comment by kookma** [comment]
I already did that using this PR: https://github.com/TiddlyWiki/TiddlyWiki5/pull/8439

**Comment by kookma** [comment]
@Jermolene 
Documentation for https://github.com/TiddlyWiki/TiddlyWiki5/pull/8439 added here!

**Comment by Jermolene** [comment]
Thanks @kookma

**Pull request merged**
