### PR TITLE
Add DiffTextWidget colors to some palettes

### PR DESCRIPTION
**Pull request by Leilei332**
Add DiffTextWidget colors to Solarized, Solar Flare, Nord, GruvboxDark, DesertSand and Twlight palette to make them display properly.

Before:

图片

After:

图片

### CODE REVIEW

**Comment by pmario** [comment]
If you have a look at the palette-manager edition: https://wikilabs.github.io/editions/palette-manager/
There are a lot of palettes, that have a WL at the end of the name. 

All of them should have DiffText colours assigned. Some feedback would be welcome. 

That's a reminder, that I should create a PR for all palettes. Since all of the core palettes have some missing elements.

**Comment by Leilei332** [comment]
There are still a lot of palettes that doesn't have `diff-*` indexes in the palette manager edition, like the two palettes:

* Solarized Light/Dark WL
* Solar Flare WL
* Spartan Day/Night WL

While those palettes have their own diff colors, which I think can be included in the PR:

* Nord WL
* DesertSand WL
* GruvboxDark WL
* Twlight WL

**Comment by pmario** [comment]
If they do not have the indexes in the palette, they use the default from vanilla. That is intended.

**Comment by kookma** [comment]
> Add DiffTextWidget colors to Solarized, Solar Flare, Nord, GruvboxDark, DesertSand and Twlight palette to make them display properly.

Thank you for using a consistent method for adding new color value! Everywhere you have use 6 chars hex code! Keep going on!

**Comment by pmario** [comment]
I think only changing the foreground-colour is not enough. We have to take "colour blindness" into account. 

Eg: this is "Nord dark" palette:  Accessibility setting: Simulate: Protanopia (no red)

image

This is the same setting, that I use with my Palette-Manager edition, with the same Accessibility setting

image

**Comment by Leilei332** [comment]
I've updated the palette to improve contrast:

图片

图片

**Pull request merged**
