### PR TITLE
Flexoki palette update

### PR DESCRIPTION
**Pull request by Leilei332**
* Add modal and selection colors to Flexoki Light palette
* Make Flexoki Light primary color darker to improve contrast
* Make Flexoki Light tiddler subtitle color lighter
* Improve Flexoki Dark contrast

### CODE REVIEW

**Comment by Jermolene** [comment]
Thank you @Leilei332

**Comment by kookma** [comment]
Thank you @Leilei332 
One question: Is the button border in the sidebar thicker and darker by design? See below images

Flexokilight
image


Vanilla
image

The border in Vanilla seems more vibrant and has better contrast

**Comment by Leilei332** [comment]
Setting `button-*` colors will cause the button border to use a different style. This happens in Solarized palettes too.

**Comment by kookma** [comment]
I think another issue should be opened to address this behavior. I will do that

**Pull request merged**
