### PR TITLE
Gather all the plugins' settings page under the control panel's "Settings" tab.

### PR DESCRIPTION
**Pull request by Leilei332**
Add `$:/tags/ControlPanel/SettingsTab` tag to all the plugins' setting page, so that they are accessible under the "Setting" tab in control panel.

### CODE REVIEW

**Comment by kookma** [comment]
This adds a good convention to TW UI. I would recommend adding a short description in official doc and encourage the plugin developer to follow this nice rule.

**Comment by kookma** [comment]
> all the plugins' setting page, so that they are accessible under the "Setting" tab

Is it possible to make TiddlyWiki appears first and all other in alphabetical order? Finding them should be easier this way!

**Comment by pmario** [comment]
@Leilei332 I think the TW plugins should go below the TiddlyWiki tab, so it is clear where the belong to. 

eg. If I would also add all my plugin settings to the main tab, it will be full. See the screenshot.

image

That's the code

```
Get an overview about all [[WikiLab Pugins|https://wikilabs.github.io]] 

<div class="tc-control-panel">
<$macrocall $name="tabs"
    tabsList="[all[shadows+tiddlers]tag[$:/tags/ControlPanel/WikiLabs]!has[draft.of]]"
    default="$:/plugins/wikilabs/uni-link/readme"
    explicitState="$:/state/tab/settings/wikilabs"
/>
</div>
```
image

**Comment by Jermolene** [comment]
Thanks @Leilei332 I think this is a step in the right direction, and would welcome any further refinements

**Pull request merged**
