### PR TITLE
Make overflowed content scrollable

### LINKED ISSUE #8523: [BUG] Better handling for overflowed content
### Describe the bug

I've encountred several times that the content of the tiddler overflows when viewing tiddlywiki on my mobile phone, which made the content looked strange.

截图 2024-08-18 21 40 27

截图 2024-08-18 21 46 01

### Expected behavior

The overflowed content are displayed properly.

### To Reproduce

_No response_

### Screenshots

_No response_

### TiddlyWiki Configuration

5.3.6-prerelease

### Additional context

I think the overflowed content should have been handled properly. IMO we can make the overflowed content displayed properly by making it scrollable. My solution is to add `overflow-x:auto` to classes including `tc-tiddler-body`, `tc-tab-content`. What do you think?

截图 2024-08-18 21 50 21

### PR DESCRIPTION
**Pull request by Leilei332**
This PR closes #8523.

Add `overflow-x: auto` to `tc-tiddler-body` and `tc-tab-content` to make overflowed content scrollable, so that overflowed content can be handled correctly.

### CODE REVIEW

**Comment by Jermolene** [comment]
Thanks @Leilei332 – I wonder if this solution might lead to scrollable areas nested within other scrollable areas? If so, I'd be concerned that it will be hard for us to assess usability across all the relevant browsers. For example, browsers configured to always show visible scrollbars might be confusing (which is already an issue with the sidebar implementation).

**Comment by pmario** [comment]
@Leilei332 -- It seems the latest changes have completely removed the tabs from all CSS rules. Is that intended?

**Comment by Leilei332** [comment]
> @Leilei332 -- It seems the latest changes have completely removed the tabs from all CSS rules. Is that intended?

I have fixed it. This is because I typed `<` in vim by mistake.

**Comment by Jermolene** [comment]
Thanks @Leilei332

**Comment by Leilei332** [comment]
Looks like `tc-scary-warning` is not capable with this PR:



Before:

**Comment by Jermolene** [comment]
Ouch thanks @Leilei332 do you have time to work on a fix?

**Comment by Jermolene** [comment]
> Looks like `tc-scary-warning` is not compatible with this PR:

On further investigation, I am inclined to think that we need to revert this PR. The ability to place content in the margins of tiddlers is important for some layouts, and so I think introducing a new scrolling context is too much of a break in backwards compatibility.

The revert is in 695e2ee5894277f78b8b8cf6d157a4121f4e9b5d

I'd welcome further exploration of a better fix.

**Comment by Leilei332** [comment]
Looks like overflow often occurs in elements like table and table of content macros. I think it may be better to only make them scrollable on overflow.

**Pull request merged**
